[package]
name = "nfl/thunderbirds-stadium"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
roact = "roblox/roact@1.4.4"
maid = "flamenco687/maid@3.2.2"
Signal = "sleitnick/signal@1.0.1"
profileservice = "surnautica/profileservice@1.0.0"
